[general]
import = [
  "~/.config/alacritty/themes/github_light_colorblind.toml"
]

[terminal]
shell.program = "/bin/zsh"
shell.args = ["-l", "-c", "zellij"]

[window]
decorations_theme_variant = "Light"
opacity = 0.90
blur = true
option_as_alt = "Both"

[font]
size = 18.0
normal = { family = "MesloLGS NF", style = "Regular" }
